### ISSUE TITLE
翻译文字里不能出现 %

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#11]
原翻译中有 `(commission fee 5%)`

```
[13:10:35 WARN]: java.util.UnknownFormatConversionException: Conversion = ')'
[13:10:35 WARN]:        at java.util.Formatter.checkText(Formatter.java:2579)
[13:10:35 WARN]:        at java.util.Formatter.parse(Formatter.java:2565)
[13:10:35 WARN]:        at java.util.Formatter.format(Formatter.java:2501)
[13:10:35 WARN]:        at java.util.Formatter.format(Formatter.java:2455)
[13:10:35 WARN]:        at java.lang.String.format(String.java:2940)
[13:10:35 WARN]:        at cat.nyaa.HamsterEcoHelper.I18n.get(I18n.java:78)
[13:10:35 WARN]:        at cat.nyaa.HamsterEcoHelper.auction.AuctionInstance.<init>(AuctionInstance.java:57)
[13:10:35 WARN]:        at cat.nyaa.HamsterEcoHelper.auction.AuctionManager.newPlayerAuction(AuctionManager.java:78)
[13:10:35 WARN]:        at cat.nyaa.HamsterEcoHelper.auction.AuctionCommands.Auc(AuctionCommands.java:128)
[13:10:35 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:10:35 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:10:35 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:10:35 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[13:10:35 WARN]:        at cat.nyaa.HamsterEcoHelper.CommandHandler.onCommand(CommandHandler.java:104)
[13:10:35 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:10:35 WARN]:        at com.massivecraft.massivelag.inject.command.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:91)
[13:10:35 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
[13:10:35 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
[13:10:35 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
[13:10:35 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:10:35 WARN]:        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[13:10:35 WARN]:        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[13:10:35 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:10:35 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:10:35 WARN]:        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[13:10:35 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[13:10:35 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[13:10:35 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[13:10:35 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[13:10:35 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by cyilin** [comment]
%需要写成%%
也就是 (commission fee 5%%)

**Comment by phoenixlzx** [comment]
GET
