### ISSUE TITLE
failed to serialize itemstack to nms item

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#13]
again - -

```
[21:29:42 ERROR]: [HamsterEcoHelper] failed to serialize itemstack to nms item
java.lang.NullPointerException
        at sun.reflect.GeneratedMethodAccessor469.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at cat.nyaa.HamsterEcoHelper.utils.ReflectionUtil.convertItemStackToJson(ReflectionUtil.java:169) [HamsterEcoHelper-1.0.26.jar:?]
        at cat.nyaa.HamsterEcoHelper.utils.Message.append(Message.java:38) [HamsterEcoHelper-1.0.26.jar:?]
        at cat.nyaa.HamsterEcoHelper.requisition.RequisitionInstance.<init>(RequisitionInstance.java:76) [HamsterEcoHelper-1.0.26.jar:?]
        at cat.nyaa.HamsterEcoHelper.requisition.RequisitionManager.newPlayerRequisition(RequisitionManager.java:70) [HamsterEcoHelper-1.0.26.jar:?]
        at cat.nyaa.HamsterEcoHelper.requisition.RequisitionCommands.Requisition(RequisitionCommands.java:155) [HamsterEcoHelper-1.0.26.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at cat.nyaa.HamsterEcoHelper.CommandHandler.onCommand(CommandHandler.java:104) [HamsterEcoHelper-1.0.26.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at com.massivecraft.massivelag.inject.command.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:91) [MassiveLag.jar:?]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by phoenixlzx** [comment]
It may occur when player requisite something with name, and empty hand.
