### ISSUE TITLE
Testing on 1.11

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/HamsterEcoHelper#16]
这个 issue 用来整理 1.11 中发现的问题

**Comment by phoenixlzx** [comment]
```
[12:21:45 INFO]: [HamsterEcoHelper] bought: {id: 2520, item: "SULPHUR:0", amount: 60, price: 6.00, player: "_NR", from: "viper_L"}
[12:21:45 ERROR]: Could not pass event InventoryClickEvent to HamsterEcoHelper v1.0.0.32
org.bukkit.event.EventException
        at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:77) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1835) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at net.minecraft.server.v1_11_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.jar:git-Spigot-16c940b-9543621]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchFieldError: ENTITY_EXPERIENCE_ORB_TOUCH
        at cat.nyaa.HamsterEcoHelper.market.MarketManager.buy(MarketManager.java:80) ~[?:?]
        at cat.nyaa.HamsterEcoHelper.Events.onInventoryClickEvent(Events.java:44) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor263.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:60) ~[?:?]
        ... 15 more
```
