### ISSUE TITLE
Travis Build Failed

### ISSUE THREAD

**Issue by felixonmars** [NyaaCat/HamsterEcoHelper#4]
Please have a look:

https://travis-ci.org/NyaaCat/HamsterEcoHelper/builds/134213275

**Comment by felixonmars** [comment]
Sorry, nvm. Fixed by specifying "oraclejdk8" as jdk version.

**Comment by phoenixlzx** [comment]
```
[10:53:08 INFO]: [HamsterEcoHelper] Enabling HamsterEcoHelper v1.0.0.5
[10:53:08 WARN]: java.lang.NullPointerException
[10:53:08 WARN]:        at cat.nyaa.HamsterEcoHelper.HamsterEcoHelper.onEnable(HamsterEcoHelper.java:38)
[10:53:08 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[10:53:08 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[10:53:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:53:08 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361)
[10:53:08 WARN]:        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321)
[10:53:08 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416)
[10:53:08 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381)
[10:53:08 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336)
[10:53:08 WARN]:        at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268)
[10:53:08 WARN]:        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[10:53:08 WARN]:        at java.lang.Thread.run(Thread.java:745)
[10:53:08 ERROR]: [HamsterEcoHelper] Plugin failed to enable
[10:53:08 INFO]: [HamsterEcoHelper] Disabling HamsterEcoHelper v1.0.0.5
```

@felixonmars @RecursiveG <(=﹁"﹁=)>
