### ISSUE TITLE
无法彻底移除牌子商店

### ISSUE THREAD

**Issue by Ghost-chu** [NyaaCat/HamsterEcoHelper#46]
按shift+左键拆了之后 放个空牌子上去 右键依然可以打开商店 lastet 1.13 pre-release

**Comment by Ghost-chu** [comment]
追加：重载或重启服务器后没此问题

**Comment by Librazy** [comment]
无法重现。在拆牌子的时候有看到 "sign removed" 和控制台 [HamsterEcoHelper] Remove sign 的提示吗？

**Comment by LeonXu98** [comment]
玩家在Ghost-chu所提的环境中（1.13 pre-release)中，玩家拆除牌子后没有返回任何信息。

**Comment by Ghost-chu** [comment]
有报错
```
[21:05:07 INFO]: [HamsterEcoHelper] 创建抽奖木牌：{player: "Ghost_chu", price: 1.0, world: "w2", x: "-47", y: "73", z:"2988"}
[21:05:07 INFO]: [HamsterEcoHelper] Connecting database: jdbc:sqlite:/vdata/stormc/data/user/Ghostchu/Main/plugins/HamsterEcoHelper/HamsterEcoHelper.db
[21:05:10 ERROR]: Could not pass event BlockBreakEvent to HamsterEcoHelper v6.1.177-mc1.13
org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at net.minecraft.server.v1_13_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:297) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:128) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1238) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_162]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_162]
at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:987) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:915) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:813) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.UnsupportedOperationException
at cat.nyaa.nyaacore.database.relational.SynchronizedQuery$NonTransactionalQuery.commit(SynchronizedQuery.java:284) ~[?:?]
at cat.nyaa.HamsterEcoHelper.database.Database.removeShopSign(Database.java:235) ~[?:?]
at cat.nyaa.HamsterEcoHelper.signshop.SignShopManager.removeSign(SignShopManager.java:179) ~[?:?]
at cat.nyaa.HamsterEcoHelper.signshop.SignShopListener.onBreakBlock(SignShopListener.java:138) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1099.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[PaperSpigot-1.13-R0.1.jar:git-Paper-138]
... 18 more
```

**Comment by cyilin** [comment]
和 #45 是一个问题，请更新到v6.1.179。
