### ISSUE TITLE
新版本无法使用

### ISSUE THREAD

**Issue by NyanMeow** [NyaaCat/HamsterEcoHelper#48]
[15:03:43 INFO]: [HamsterEcoHelper] Enabling HamsterEcoHelper v6.1.179-mc1.13
[15:03:43 INFO]: [HamsterEcoHelper] Now using language: zh_CN
[15:03:43 ERROR]: Error occurred while enabling HamsterEcoHelper v6.1.179-mc1.13 (Is it up to date?)
java.lang.NullPointerException: null
        at java.io.File.<init>(File.java:360) ~[?:1.8.0_181]
        at cat.nyaa.nyaacore.database.provider.SQLiteDatabase.newConnection(SQLiteDatabase.java:44) ~[?:?]
        at cat.nyaa.nyaacore.database.provider.SQLiteDatabase.<init>(SQLiteDatabase.java:23) ~[?:?]
        at cat.nyaa.nyaacore.database.provider.SQLiteProvider.get(SQLiteProvider.java:15) ~[?:?]
        at cat.nyaa.nyaacore.database.DatabaseUtils.get(DatabaseUtils.java:66) ~[?:?]
        at cat.nyaa.nyaacore.database.DatabaseUtils.get(DatabaseUtils.java:85) ~[?:?]
        at cat.nyaa.nyaacore.database.DatabaseUtils.get(DatabaseUtils.java:113) ~[?:?]
        at cat.nyaa.HamsterEcoHelper.database.Database.<init>(Database.java:25) ~[?:?]
        at cat.nyaa.HamsterEcoHelper.HamsterEcoHelper.onEnable(HamsterEcoHelper.java:49) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:426) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:340) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-fe3ab0d-3418f8d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[15:03:43 INFO]: [NyaaUtils] Enabling NyaaUtils v6.1.209-mc1.13
[15:03:43 INFO]: [NyaaUtils] Now using language: zh_CN
[15:03:43 INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:03:44 INFO]: Time elapsed: 21429 ms
[15:03:44 INFO]: Done (24.258s)! For help, type "help"

**Comment by cyilin** [comment]
配置文件里缺少数据库的配置信息

需要把这部分复制到配置文件里 https://github.com/NyaaCat/HamsterEcoHelper/blob/master/src/main/resources/config.yml#L13
