### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by NyanMeow** [NyaaCat/HamsterEcoHelper#49]
前几天服蹦了之后再打开就发现heh无法使用了
报错：
``` [19:20:53] [Server thread/ERROR]: Error occurred while enabling HamsterEcoHelper v3.0.0.182 (Is it up to date?)
java.lang.NoClassDefFoundError: cat/nyaa/nyaacore/database/SQLiteDatabase
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_102]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_102]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:150) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at cat.nyaa.HamsterEcoHelper.HamsterEcoHelper.onEnable(HamsterEcoHelper.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:582) [spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:545) [spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:423) [spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]
Caused by: java.lang.ClassNotFoundException: cat.nyaa.nyaacore.database.SQLiteDatabase
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_102]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.13.1.jar:git-Spigot-0ede7d0-632449b]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_102]
	... 21 more
[19:20:53] [Server thread/INFO]: [NyaaUtils] Enabling NyaaUtils v6.1.210-mc1.13
[19:20:53] [Server thread/INFO]: [NyaaUtils] Now using language: zh_CN
[19:20:53] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:20:54] [Server thread/INFO]: Done (23.460s)! For help, type "help"
[19:20:54] [Server thread/INFO]: Using default channel type
[19:20:56] [Server thread/INFO]: [PlaceholderAPI] An update for PlaceholderAPI (v2.9.2) is available at:
[19:20:56] [Server thread/INFO]: [PlaceholderAPI] https://www.spigotmc.org/resources/placeholderapi.6245/
[19:20:57] [Craft Scheduler Thread - 2/INFO]: [PlaceholderAPI] 122 placeholder expansions are available on the cloud.
[19:21:23] [Server thread/INFO]: Only players can do this[m
[19:21:31] [Server thread/WARN]: java.lang.NullPointerException
[19:21:31] [Server thread/WARN]: 	at cat.nyaa.HamsterEcoHelper.balance.BalanceCommands.viewbalance(BalanceCommands.java:97)
[19:21:31] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:21:31] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:21:31] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:21:31] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:21:31] [Server thread/WARN]: 	at cat.nyaa.nyaacore.CommandReceiver.acceptCommand(CommandReceiver.java:204)
[19:21:31] [Server thread/WARN]: 	at cat.nyaa.nyaacore.CommandReceiver.acceptCommand(CommandReceiver.java:202)
[19:21:31] [Server thread/WARN]: 	at cat.nyaa.nyaacore.CommandReceiver.onCommand(CommandReceiver.java:177)
[19:21:31] [Server thread/WARN]: 	at cat.nyaa.HamsterEcoHelper.CommandHandler.onCommand(CommandHandler.java:74)
[19:21:31] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:21:31] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[19:21:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:695)
[19:21:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:680)
[19:21:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.aU(DedicatedServer.java:453)
[19:21:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:412)
[19:21:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[19:21:31] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[19:21:31] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:21:31] [Server thread/INFO]: Internal server error. Unable to run command ```

**Comment by Librazy** [comment]
nc与nu版本不匹配，回滚或者更新其中一个就好了。

**Comment by NyanMeow** [comment]
![TIM截图20180912173308.png](https://i.loli.net/2018/09/12/5b98dd63030d5.png)
hmm.我的锅下插件的时候以为第一个是最新的，然而却是1.12的。而1.13.1的在下面喵。。。
