### ISSUE TITLE
RunTime Exception: 无法成功使用MySQL

### ISSUE THREAD

**Issue by Akiranya** [NyaaCat/HamsterEcoHelper#50]
**server version**
`This server is running Paper version git-Paper-488 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

**error log**
```
[15:17:14 INFO]: [NyaaCore] Enabling NyaaCore v6.3.295-mc1.13.2
[15:17:14 INFO]: [HamsterEcoHelper] Enabling HamsterEcoHelper v6.2.207-mc1.13.2
[15:17:14 INFO]: [HamsterEcoHelper] Now using language: zh_CN
[15:17:15 WARN]: Fri Dec 28 15:17:15 CST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[15:17:15 ERROR]: Error occurred while enabling HamsterEcoHelper v6.2.207-mc1.13.2 (Is it up to date?)
java.lang.RuntimeException: CREATE TABLE IF NOT EXISTS signshop_location(id MEDIUMTEXT,lotto_price DOUBLE,mode MEDIUMTEXT,owner MEDIUMTEXT,world MEDIUMTEXT,x BIGINT,y BIGINT,z BIGINT,CONSTRAINT constraint_PK PRIMARY KEY (id))
        at cat.nyaa.nyaacore.database.relational.BaseDatabase.createTable(BaseDatabase.java:122) ~[?:?]
        at cat.nyaa.nyaacore.database.relational.BaseDatabase.query(BaseDatabase.java:180) ~[?:?]
        at cat.nyaa.nyaacore.database.relational.BaseDatabase.query(BaseDatabase.java:21) ~[?:?]
        at cat.nyaa.HamsterEcoHelper.database.Database.getShopSigns(Database.java:197) ~[?:?]
        at cat.nyaa.HamsterEcoHelper.signshop.SignShopManager.<init>(SignShopManager.java:33) ~[?:?]
        at cat.nyaa.HamsterEcoHelper.HamsterEcoHelper.onEnable(HamsterEcoHelper.java:60) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:441) ~[patched_1.13.2.jar:git-Paper-488]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:355) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:613) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:575) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:435) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-488]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791) ~[patched_1.13.2.jar:git-Paper-488]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'id' used in key specification without a key length
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_191]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_191]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[patched_1.13.2.jar:git-Paper-488]
        at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[patched_1.13.2.jar:git-Paper-488]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[patched_1.13.2.jar:git-Paper-488]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978) ~[patched_1.13.2.jar:git-Paper-488]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914) ~[patched_1.13.2.jar:git-Paper-488]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[patched_1.13.2.jar:git-Paper-488]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[patched_1.13.2.jar:git-Paper-488]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491) ~[patched_1.13.2.jar:git-Paper-488]
        at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1552) ~[patched_1.13.2.jar:git-Paper-488]
        at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2607) ~[patched_1.13.2.jar:git-Paper-488]
        at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1480) ~[patched_1.13.2.jar:git-Paper-488]
        at cat.nyaa.nyaacore.database.relational.BaseDatabase.createTable(BaseDatabase.java:119) ~[?:?]
        ... 16 more
[15:17:15 INFO]: [HamsterEcoHelper] Disabling HamsterEcoHelper v6.2.207-mc1.13.2
[15:17:15 INFO]: [NyaaUtils] Enabling NyaaUtils v6.1.234-mc1.13.2
[15:17:15 INFO]: [NyaaUtils] Now using language: zh_CN

```

**heh config**
```
# 
# default 120 sec
language: zh_CN
auctionIntervalTicks: 72000
bidTimeoutTicks: 600
marketPlaySound: true
marketBroadcast: true
marketBroadcastCooldown: 120
database:
  provider: mysql
  connection:
    autoscan: true
    package: cat.nyaa.HamsterEcoHelper.database
    url: jdbc:mysql://localhost:3306/reborn
    username: bleh
    password: blah
requisitionIntervalTicks: 72000
auctionMaxDelayTicks: 2000
requisitionMaxDelayTicks: 2000
auctionMinimalPlayer: 5
requisitionMinimalPlayer: 2
requisitionHintInterval: 600
market_tax: 5
market_offer_fee: 10
market_placement_fee: 1
playerAuctionTimeoutTicks: 1000
playerAuctionCooldownTicks: 3000
playerAuctionCommissionFee: 0
playerRequisitionTimeoutTicks: 1000
playerRequisitionCooldownTicks: 3000
enable_balance: false
balance_SaveIntervalTicks: 12000
system_balance_log: false
death_penalty:
  worlds: []
  penalty:
    min: 100
    max: 1000
    percent: 10
signshop:
  tax: 0
  sign_limit: {}
  slot_limit: {}
ads:
  interval: 600
  count_afk: false
  count_self: false
  price: 5
  max_display: 100
  min_display: 20
  color: true
  formatting: []
  limit_total: 100
  limit_text: 50
  limit_group: {}
lotto:
  force_locked: false
search:
  cooldown_tick: 200
  lore_additional_tick: 200
  ench_additional_tick: 200
transaction:
  active_time_out_tick: 12000
  max_open_sellside: 20
  list_closed_per_page: 5
  tax: 5
  require_confirm_seller: false
database_version: 1
signshop_yaml_to_nbt: true
marketSlot:
  default: 10
  builder: 15
```

**Comment by Akiranya** [comment]
**Sorry, I forgot about my MySQL version**
`mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper`
