### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by DSgerr** [NyaaCat/HamsterEcoHelper#54]
开服后第一次进服没有报错,退出重进之后就报错了
如下:
[12:31:31] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to HamsterEcoHelper v6.2.220-mc1.13.2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:343) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:162) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:149) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.LoginListener.tick(LoginListener.java:53) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:230) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:119) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [start.jar:git-Spigot-3cb9dcb-40cbae4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.RuntimeException: SELECT COUNT(*) AS C FROM temporary_storage WHERE player_id=?
	at cat.nyaa.nyaacore.database.relational.SynchronizedQuery.count(SynchronizedQuery.java:208) ~[?:?]
	at cat.nyaa.HamsterEcoHelper.database.Database.getTemporaryStorage(Database.java:36) ~[?:?]
	at cat.nyaa.HamsterEcoHelper.Events.onPlayerJoin(Events.java:43) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	... 14 more
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: temporary_storage)
	at org.sqlite.core.DB.newSQLException(DB.java:941) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.core.DB.newSQLException(DB.java:953) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.core.DB.throwex(DB.java:918) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:134) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.core.DB.prepare(DB.java:257) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	at cat.nyaa.nyaacore.database.relational.SynchronizedQuery.count(SynchronizedQuery.java:193) ~[?:?]
	at cat.nyaa.HamsterEcoHelper.database.Database.getTemporaryStorage(Database.java:36) ~[?:?]
	at cat.nyaa.HamsterEcoHelper.Events.onPlayerJoin(Events.java:43) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[start.jar:git-Spigot-3cb9dcb-40cbae4]
	... 14 more

插件列表:
EssentialsX-2.16.1.0
EssentialsXSpawn-2.16.1.0
LangUtils-1.9
NyaaCore-v6.3.318-mc1.13.2
Vault

**Comment by EbonyMementoMori** [comment]
我也有相同的问题
